// <auto-generated />
namespace Vidly_Clone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeedUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202206060610134_SeedUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
